name: dagger
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "🎉 Run Tests"
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
